[package]
name = "protobuf_demo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.9"

[build-dependencies]
prost-build = "0.11.9"
protobuf-src = "1.1.0"
